"""Add meeting_link column

Revision ID: 0be602db54fb
Revises: f889b99309cb
Create Date: 2025-09-03 17:50:56.200023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0be602db54fb'
down_revision = 'f889b99309cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meeting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meeting_link', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('audio_path', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('transcript_source', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meeting', schema=None) as batch_op:
        batch_op.drop_column('transcript_source')
        batch_op.drop_column('audio_path')
        batch_op.drop_column('meeting_link')

    # ### end Alembic commands ###
